openapi: 3.0.3
info:
  title: PIN Authentication API
  description: API endpoints for PIN authentication layer
  version: 1.0.0

servers:
  - url: /api
    description: Local API

paths:
  /pin/create:
    post:
      summary: Create or update user PIN
      description: Sets a new PIN for the authenticated user. Requires PIN confirmation.
      tags:
        - PIN
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - pin
                - confirm_pin
              properties:
                pin:
                  type: string
                  pattern: "^[0-9]{4}$"
                  description: 4-digit PIN
                  example: "1234"
                confirm_pin:
                  type: string
                  pattern: "^[0-9]{4}$"
                  description: PIN confirmation (must match pin)
                  example: "1234"
      responses:
        "200":
          description: PIN created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "PIN created successfully"
        "400":
          description: Invalid input or PINs don't match
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Not authenticated (no trainer_id cookie)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /pin/verify:
    post:
      summary: Verify user PIN
      description: Validates the PIN for session access. Tracks failed attempts and lockouts.
      tags:
        - PIN
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - pin
              properties:
                pin:
                  type: string
                  pattern: "^[0-9]{4}$"
                  description: 4-digit PIN to verify
                  example: "1234"
      responses:
        "200":
          description: PIN verification result
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                    description: Whether PIN was correct
                  must_change:
                    type: boolean
                    description: True if temporary PIN requires change
                  message:
                    type: string
                    description: User-facing message (for temp PIN prompt)
                    example: "Your PIN was reset by support. Please create a new PIN."
        "400":
          description: Invalid PIN format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "423":
          description: Account locked due to failed attempts
          content:
            application/json:
              schema:
                type: object
                properties:
                  locked:
                    type: boolean
                    example: true
                  lockout_remaining_seconds:
                    type: integer
                    description: Seconds until lockout expires
                    example: 847
                  message:
                    type: string
                    example: "Account locked. Try again in 14 minutes."

  /pin/status:
    get:
      summary: Get PIN status for current user
      description: Returns whether user has PIN set, is locked, etc.
      tags:
        - PIN
      responses:
        "200":
          description: PIN status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PinStatus"
        "401":
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /pin/admin/reset:
    post:
      summary: Admin - Reset user PIN
      description: Clears user's PIN, forcing them to create a new one. Admin only.
      tags:
        - PIN Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
              properties:
                user_id:
                  type: string
                  format: uuid
                  description: Target user ID
      responses:
        "200":
          description: PIN reset successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "PIN reset successfully"
        "401":
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Not authorized (not admin)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /pin/admin/unlock:
    post:
      summary: Admin - Unlock user account
      description: Clears lockout and failed attempt count. Admin only.
      tags:
        - PIN Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
              properties:
                user_id:
                  type: string
                  format: uuid
                  description: Target user ID
      responses:
        "200":
          description: Account unlocked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Account unlocked successfully"
        "401":
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Not authorized (not admin)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /pin/admin/set-temp:
    post:
      summary: Admin - Set temporary PIN
      description: Sets a temporary PIN that user must change on first login. Admin only.
      tags:
        - PIN Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - pin
              properties:
                user_id:
                  type: string
                  format: uuid
                  description: Target user ID
                pin:
                  type: string
                  pattern: "^[0-9]{4}$"
                  description: Temporary 4-digit PIN
                  example: "0000"
      responses:
        "200":
          description: Temporary PIN set successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Temporary PIN set successfully"
        "400":
          description: Invalid PIN format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Not authorized (not admin)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: "Invalid PIN format"

    PinStatus:
      type: object
      properties:
        has_pin:
          type: boolean
          description: Whether user has a PIN set
        is_locked:
          type: boolean
          description: Whether account is currently locked
        is_temporary:
          type: boolean
          description: Whether current PIN is temporary (requires change)
        lockout_remaining_seconds:
          type: integer
          description: Seconds until lockout expires (only if locked)

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: trainer_id
      description: Trainer session cookie

security:
  - cookieAuth: []

tags:
  - name: PIN
    description: User PIN operations
  - name: PIN Admin
    description: Admin PIN management (requires admin role)
